#!/bin/bash -
#====================================================================
#
#   DESCRIPTION: on Debian-based systems, installs dependencies for
#   blather, gets source code for sphinx stuff, builds, installs
#   program, config files, and so forth. USE AT YOUR OWN RISK!
#   READ THE SCRIPT CAREFULLY AND DECIDE IF YOU WANT TO USE IT
#
#  REQUIREMENTS: debian-based system, sudo privileges
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Jonathan Kulp ()
#       CREATED: 07/09/2013 09:03:38 PM CDT
#====================================================================

user=$(whoami)
builddir="$HOME/blather"
configdir="$HOME/.config/blather"
voice="flite"

install_deps(){
  buildtools="git flite espeak build-essential gnome-common bison"
  libs="python-pyside libgstreamer-plugins-base0.10-dev libgstreamer0.10-cil-dev libgstreamer0.10-dev python-gst0.10-dev rygel-gst-launch gstreamer0.10-plugins-good python-sphinx gstreamer0.10-tools python-gtk2 python-gtk2-dev"
  packages="xvkbd xdotool $voice wmctrl elinks xclip curl"
  sudo apt-get update
  sudo apt-get install $buildtools $libs $packages
}

get_sphinx(){
  version="0.8"
  cd
  wget http://sourceforge.net/projects/cmusphinx/files/sphinxbase/$version/sphinxbase-$version.tar.gz
  tar xvf sphinxbase-$version.tar.gz
  cd sphinxbase-$version/
  ./autogen.sh && make && sudo make install
}

get_pocketsphinx(){
  version="0.8"
  cd
  wget http://sourceforge.net/projects/cmusphinx/files/pocketsphinx/$version/pocketsphinx-$version.tar.gz
  tar xvf pocketsphinx-$version.tar.gz
  cd pocketsphinx-$version/
  ./autogen.sh && make && sudo make install
  sudo cp ./src/gst-plugin/.libs/libgstpocketsphinx.so /usr/local/lib/gstreamer-0.10/
}

get_blather(){
  cd
  git clone https://github.com/itsdarklikehell/blather
}

conf(){
startupscript=$HOME/blather/blather.sh
# mkdir -p $configdir
# cp -R $builddir/config/ $configdir/
# cp $builddir/options.yaml.tmp $configdir/options.yaml

# create a startup script
cat > $startupscript << EOFstartup
#!/bin/bash

# tell it where the Gstreamer libraries are located

export GST_PLUGIN_PATH=/usr/local/lib/gstreamer-0.10
sleep .1

# set some shortcuts to use in the commands file

#export VOICE="/usr/bin/festival --tts"
export VOICE="/usr/bin/flite"
#export VOICE="/usr/bin/espeak"
sleep .1
export PLUGINS="$HOME/blather/config/plugins"
sleep .1
export CONFIGDIR="$HOME/blather/config"
sleep .1
export CLIP="$HOME/.local/share/clipit/history"
sleep .1
# export KEYPRESS="xvkbd -xsendevent -secure -text"
export KEYPRESS="xdotool key"
sleep .1
export KEYHOLD="xdotool keydown"
sleep .1
export KEYTYPE="xdotool type"
sleep .1
export MMOVE="xdotool mousemove"
# XCOORD:YCOORD
sleep .1
export CLICK="xdotool click"
# Generally, left = 1, middle = 2, right = 3, wheel up = 4, wheel down = 5
sleep .1
export BROWSER="firefox"
sleep .1
export CHBROWSER="google-chrome"
sleep .1
export CRMBROWSER="chromium-browser"
sleep .1
export EDITOR="geany"
#export EDITOR="atom"
sleep .1
export FM="pcmanfm"
#export FM="thunar"
sleep .3

# start blather in continuous mode with the GTK GUI
# and a history of 20 recent commands
$HOME/blather/./language_updater.sh
python2 $HOME/blather/Blather.py

EOFstartup

chmod +x $startupscript
sudo ln -s $startupscript /usr/local/bin/blather
sudo ln -s $HOME/blather/blather-gtk.sh /usr/local/bin/blather-gtk
sudo ln -s $HOME/blather/blather-qt.sh /usr/local/bin/blather-qt
}
echo "installing dependencies" | $voice
install_deps
echo "Done!" | $voice
echo "installing sphinxbase" | $voice
get_sphinx
echo "Done!" | $voice
echo "installing pocketsphinx" | $voice
get_pocketsphinx
echo "Done!" | $voice
echo "installing Blather" | $voice
get_blather
echo "Done!" | $voice
echo "configuring blather" | $voice
conf
echo "Done!" | $voice
exit 0
